# Generated by Django 5.0.6 on 2024-07-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_ID', models.IntegerField()),
                ('Date', models.DateField()),
                ('Product_ID', models.CharField(max_length=100)),
                ('Quantity_Sold', models.IntegerField()),
                ('Total_Sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Top_Selling_Product', models.CharField(max_length=50)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_date', to='EmailReport.salesdata')),
                ('Store_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_store_id', to='EmailReport.salesdata')),
                ('Total_Sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_total_sales', to='EmailReport.salesdata')),
            ],
        ),
    ]
