# Generated by Django 5.0.6 on 2024-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='Store_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='Total_Sales',
            field=models.IntegerField(),
        ),
    ]
