# Generated by Django 5.0.6 on 2024-07-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailReport', '0002_alter_summary_date_alter_summary_store_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='ProcessedData',
        ),
        migrations.RenameModel(
            old_name='SalesData',
            new_name='RawData',
        ),
    ]
